name: Build SwitchColor15

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1

      - name: Build tweak
        run: |
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: List packages
        run: |
          ls -lah packages/

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: SwitchColor15-v0.5.1
          path: packages/*.deb
