name: Build SwitchColor15

'on':
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Theos
        uses: Randomblock1/theos-action@v1

      - name: Comprobar archivos
        run: |
          echo "=== DIRECTORIO ==="
          pwd
          echo "=== ARCHIVOS ==="
          ls -la
          echo "=== TWEAK.XM ==="
          find . -name "Tweak.xm" -print
          echo "=== MAKEFILE ==="
          cat Makefile

      - name: Compilar tweak
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Subir DEB
        uses: actions/upload-artifact@v4
        with:
          name: SwitchColor15-deb
          path: packages/*.deb
